### PR TITLE
Check .github/ghstack_direct to decide if using direct by default

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #258

**Review by kirklandsign — COMMENTED** [review]
Thank you! That's a useful feature!

**Comment by ezyang** [comment]
@kirklandsign Do you have an opinion about whether or not I should flip the default so `--direct` by default, and the other behavior only if there's a different signal file?

**Comment by kirklandsign** [comment]
> @kirklandsign Do you have an opinion about whether or not I should flip the default so `--direct` by default, and the other behavior only if there's a different signal file?

To our use case checking `.github/ghstack_direct` without flipping the default value works, and it causes minimal behavior changes to users who are already using ghstack in other repos like pytorch/pytorch otherwise.

**Pull request merged**
