### PR TITLE
Don't unexpectedly merge when commits are reordered

### LINKED ISSUE #23: PR unexpectedly merged when commits are reordered
I had a stack of 4 PRs, like this:

1. `PR A`
2. `PR B`
3. `PR C`
4. `PR D`

`PR A` was taking a while to review, so I rebased my stack to put it at the end:

1. `PR B`
2. `PR C`
3. `PR D`
4. `PR A`

But for some reason, after I ran `ghstack`, `PR A` got merged (!)

At first I thought I misclicked, but this is the second time it's happened to me.

## Log

```
$ git remote get-url origin
$ git fetch origin
$ git merge-base origin/dev HEAD
$ git rev-list --header ^2f730d04bea150a5ac4cdd00a9903b7206d1a523 HEAD
$ git rev-list --header ^2f730d04bea150a5ac4cdd00a9903b7206d1a523^@ 2f730d04bea150a5ac4cdd00a9903b7206d1a523
$ git rev-list --max-count=1 --header origin/gh/uycire/23/orig
Pushing to #15173
$ git rev-parse origin/gh/uycire/23/base
$ git merge-base --is-ancestor origin/gh/uycire/23/base 2f730d04bea150a5ac4cdd00a9903b7206d1a523
$ git commit-tree f3870cc051da430fbb658597890e5f5af73d2aee -p origin/gh/uycire/23/base -p 2f730d04bea150a5ac4cdd00a9903b7206d1a523
$ git rev-parse c1614293dbd668e61ac7bb15bc34ded9187d1f94~^{tree}
$ git commit-tree dbfadf306f49558ed6eb704ec9bdd285a5971d55 -p origin/gh/uycire/23/head -p 58aba48019cbf29bce99550d02324eefe6a6be1d
Restacking commit on 2f730d04bea150a5ac4cdd00a9903b7206d1a523
$ git commit-tree dbfadf306f49558ed6eb704ec9bdd285a5971d55 -p 2f730d04bea150a5ac4cdd00a9903b7206d1a523
$ git rev-list --max-count=1 --header origin/gh/uycire/24/orig
Pushing to #15174
$ git rev-parse origin/gh/uycire/24/base
$ git merge-base --is-ancestor origin/gh/uycire/24/base 1179b46a16042a70e8ebf841278e395acf5ef622
$ git rev-parse b6e9506a067ba95070a4fd373299c959c68cdf14~^{tree}
$ git commit-tree fcd7930234022d4f51d98b5e2ae2df96d9e0786f -p origin/gh/uycire/24/head -p 1179b46a16042a70e8ebf841278e395acf5ef622
Restacking commit on ee28d0e1ab0ae29c708224a48bde2ed40d639684
$ git commit-tree fcd7930234022d4f51d98b5e2ae2df96d9e0786f -p ee28d0e1ab0ae29c708224a48bde2ed40d639684
$ git rev-list --max-count=1 --header origin/gh/uycire/34/orig
Pushing to #15214
$ git rev-parse origin/gh/uycire/34/base
$ git merge-base --is-ancestor origin/gh/uycire/34/base bed81715a6983c25786741de018a111e36a5e901
$ git rev-parse e0858fea3333550cd06a601ce42ace508d25daa2~^{tree}
$ git commit-tree dafe580de6588db31ac4b393531ad5f4a4b6550b -p origin/gh/uycire/34/head -p bed81715a6983c25786741de018a111e36a5e901
Restacking commit on 462d714e2b4e358db54715c1101b9d466ae19f5d
$ git commit-tree dafe580de6588db31ac4b393531ad5f4a4b6550b -p 462d714e2b4e358db54715c1101b9d466ae19f5d
$ git rev-list --max-count=1 --header origin/gh/uycire/22/orig
Pushing to #15167
$ git rev-parse origin/gh/uycire/22/base
$ git merge-base --is-ancestor origin/gh/uycire/22/base 93ea4d8d70e5310ded9411bab98213ed798377a4
$ git rev-parse e0f74da1612150f476eb54d9cc0417ab14dfd421~^{tree}
$ git commit-tree 2bab0f9f6aebf106b6ffa73f847f447e38bb8220 -p origin/gh/uycire/22/head -p 93ea4d8d70e5310ded9411bab98213ed798377a4
Restacking commit on cb0471ac2de373b973f13becd25affcbf0d6eb03
$ git commit-tree 2bab0f9f6aebf106b6ffa73f847f447e38bb8220 -p cb0471ac2de373b973f13becd25affcbf0d6eb03
$ git reset --soft 3ee46301fe403da8c7258003fcd18ae61d8c8155
# Updating https://github.com/benchling/aurelia/pull/15173
# Updating https://github.com/benchling/aurelia/pull/15174
# Updating https://github.com/benchling/aurelia/pull/15214
# Updating https://github.com/benchling/aurelia/pull/15167
$ git push origin 58aba48019cbf29bce99550d02324eefe6a6be1d:refs/heads/gh/uycire/23/base 1179b46a16042a70e8ebf841278e395acf5ef622:refs/heads/gh/uycir
e/24/base bed81715a6983c25786741de018a111e36a5e901:refs/heads/gh/uycire/34/base 93ea4d8d70e5310ded9411bab98213ed798377a4:refs/heads/gh/uycire/22/bas
e
To github.com:benchling/aurelia.git
   6482da57fb..93ea4d8d70  93ea4d8d70e5310ded9411bab98213ed798377a4 -> gh/uycire/22/base
   f2a04320da..58aba48019  58aba48019cbf29bce99550d02324eefe6a6be1d -> gh/uycire/23/base
   616f8d5ef0..1179b46a16  1179b46a16042a70e8ebf841278e395acf5ef622 -> gh/uycire/24/base
   ddcc776f27..bed81715a6  bed81715a6983c25786741de018a111e36a5e901 -> gh/uycire/34/base
$ git push origin 1179b46a16042a70e8ebf841278e395acf5ef622:refs/heads/gh/uycire/23/head bed81715a6983c25786741de018a111e36a5e901:refs/heads/gh/uycir
e/24/head 93ea4d8d70e5310ded9411bab98213ed798377a4:refs/heads/gh/uycire/34/head eff85617349d7019a1755f2dbcc38ada0a410f72:refs/heads/gh/uycire/22/hea
d
To github.com:benchling/aurelia.git
 ! [remote rejected]       eff85617349d7019a1755f2dbcc38ada0a410f72 -> gh/uycire/22/head (cannot lock ref 'refs/heads/gh/uycire/22/head': unable to
resolve reference 'refs/heads/gh/uycire/22/head')
 ! [remote rejected]       1179b46a16042a70e8ebf841278e395acf5ef622 -> gh/uycire/23/head (failed)
 ! [remote rejected]       bed81715a6983c25786741de018a111e36a5e901 -> gh/uycire/24/head (failed)
 ! [remote rejected]       93ea4d8d70e5310ded9411bab98213ed798377a4 -> gh/uycire/34/head (failed)
error: failed to push some refs to 'git@github.com:benchling/aurelia.git'
ERROR: Fatal exception
Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/3.8.1/lib/python3.8/site-packages/ghstack/logging.py", line 108, in manager
    yield
  File "/home/eric/.pyenv/versions/3.8.1/lib/python3.8/site-packages/ghstack/__main__.py", line 107, in main
    ghstack.submit.main(
  File "/home/eric/.pyenv/versions/3.8.1/lib/python3.8/site-packages/ghstack/submit.py", line 213, in main
    submitter.push_updates()
  File "/home/eric/.pyenv/versions/3.8.1/lib/python3.8/site-packages/ghstack/submit.py", line 985, in push_updates
    self.sh.git("push", self.remote_name, *push_branches)
  File "/home/eric/.pyenv/versions/3.8.1/lib/python3.8/site-packages/ghstack/shell.py", line 272, in git
    return self._maybe_rstrip(self.sh(*(("git",) + args), **kwargs))
  File "/home/eric/.pyenv/versions/3.8.1/lib/python3.8/site-packages/ghstack/shell.py", line 211, in sh
    raise RuntimeError(
RuntimeError: git push origin 1179b46a16042a70e8ebf841278e395acf5ef622:refs/heads/gh/uycire/23/head bed81715a6983c25786741de018a111e36a5e901:refs/h$ads/gh/uycire/24/head 93ea4d8d70e5310ded9411bab98213ed798377a4:refs/heads/gh/uycire/34/head eff85617349d7019a1755f2dbcc38ada0a410f72:refs/heads/gh/$ycire/22/head failed with exit code 1
```

### PR DESCRIPTION
**Pull request by samestep**
Closes #23.

Let's say we have a stack with two commits (listed here in reverse chronological order):

- `gh/user/Y`
- `gh/user/X`

Let's say that `origin/gh/user/Y/base` is out of date, and we run `ghstack` to update these on GitHub.

- Currently, `origin/gh/user/Y/base` is an ancestor of (local) `gh/user/X/head`, then we update `origin/gh/user/Y/base` to be `gh/user/X/head`. Otherwise, we update `origin/gh/user/Y/base` to be a merge commit whose parents are:
  - (the previous) `origin/gh/user/Y/base`
  - (the new) `gh/user/X/head`
- After this PR, regardless of any ancestral relationship, if `origin/gh/user/Y/base` is not equal to `gh/user/X/head`, we update `origin/gh/user/Y/base` to be a new commit whose _only parent_ is (the previous) `origin/gh/user/Y/base`.

This reduces the number of cases in which `base` commits end up as descendants for `head` commits from other parts of the stack.

---

This PR adds `test_ghstack.py::TestGh::test_reorder` to check a commit reordering scenario similar to the one given in the linked issue. In the test, this is the repository state before reordering:

```
* rMRG2 (gh/ezyang/2/head) Commit 2
* rMRG1 (gh/ezyang/2/base, gh/ezyang/1/head) Commit 1
* rINI0 (HEAD -> master, gh/ezyang/1/base) Initial commit
```

If you run the test without the changes introduced in this PR, this is what the final "Repository state" looks like:

```
*   rMRG1A (gh/ezyang/1/head) Reorder on "Commit 1"
|\
| *   rMRG2A (gh/ezyang/2/head, gh/ezyang/1/base) Reorder on "Commit 2"
| |\
| | * rINI2A (gh/ezyang/2/base) Update base for Reorder on "Commit 2"
| |/|
|/| |
| * | rMRG2 Commit 2
|/ /
* / rMRG1 Commit 1
|/
* rINI0 (HEAD -> master) Initial commit
```

The order of operations to get to this point is important:

1. we reorder the commits and run `ghstack`
2. `ghstack` [pushes the `base` branches first](https://github.com/ezyang/ghstack/blob/ee8f60485a868db13eb1270175346693e0626957/ghstack/submit.py#L953-L977)
3. then `ghstack` pushes the `head` branches
4. finally, `ghstack` pushes the `orig` branches (not shown here)

This means that after step 2 (but before step 3), we have the following:

- `gh/ezyang/1/head` points to `rMRG1`
- `gh/ezyang/1/base` points to `rMRG2A`

But `rMRG1` is an ancestor of `rMRG2A`! Thus from GitHub's perspective, `gh/ezyang/1/head` has been merged into `gh/ezyang/1/base`, so it marks the PR as merged. Updating `gh/ezyang/1/head` after this point doesn't actually do anything to the PR.

In contrast, this is the final repository state of the test using the changes in this PR:

```
*   rMRG1A (gh/ezyang/1/head) Reorder on "Commit 1"
|\
| * rINI1A (gh/ezyang/1/base) Update base for Reorder on "Commit 1"
| | *   rMRG2A (gh/ezyang/2/head) Reorder on "Commit 2"
| | |\
| | | * rINI2A (gh/ezyang/2/base) Update base for Reorder on "Commit 2"
| |_|/
|/| |
| | * rMRG2 Commit 2
| |/
|/|
* | rMRG1 Commit 1
|/
* rINI0 (HEAD -> master) Initial commit
```

As shown, neither new `base` commit is a descendant of its respective former `head` commit, so neither PR gets prematurely marked as merged.

---

This PR also changes a few existing tests in `test_ghstack.py::TestGh`:

- `test_amend_bottom`
- `test_amend_all`
- `test_rebase`
- `test_cherry_pick`
- `test_remove_bottom_commit`

Most of these seem fine, but the `test_rebase` and `test_cherry_pick` changes are a bit concerning, because the result is that after we update `master`, the updated `master` commit still isn't actually an ancestor of our `base` or `head` branches.

### CODE REVIEW

**Comment by samestep** [comment]
Given the issues shown by `test_rebase` and `test_cherry_pick` with the current version of this PR, I'm thinking we'll need to make the logic in this PR a bit more complicated, to allow for the base of the whole stack to be updated, without accidentally making `head` commits ancestors of their corresponding `base` commits.

**Comment by ezyang** [comment]
So, while I agree that rINI2 not showing up in the final merge graph in `test_rebase` is suboptimal (and the "fancy" behavior in the original version of ghstack was engineered around making sure rINI2 made sense), I'm not as convinced as you are that it is *wrong*.

To state the problem differently: previously, ghstack tried to accurately represent the rebase workflow as a series of incremental merges. But if I do an interactive, reordering rebase, what is the *desired* mergey version of the history?

Rebase A1 and B1 onto M2:

```
-- M1 -- M2
    \    \
     \   A2 -- B2
      \ /     /
       A1 -- B1
```

Reorder A1 and B1

```
-- M1 -----    ???
    \      \     \
     \      B2 -- A2
      \      \
       A1 -- B1
```

I'd argue that there is just no way to do it in the merge only view fo the universe, so we might as well not even try.

A simple patch to solve the "but I want master commits to be reachable" might just be to add an extra master merge base if you detect that master has advanced in the rebased stack but the merge base isn't there yet. But remember that this merge base is still going to be inaccurate if you rebase your commits *backwards* in time!

**Comment by samestep** [comment]
@ezyang That makes sense I think; I'm still pondering your second example but I see the gist of what you're saying. What I've been wondering is: assuming that it's not possible to always construct a consistent mergey history, why not just use an actual stack of commits (e.g. have `head` and `base` just point to commits on `orig`) and force-push when we need to? I'm guessing there's a good reason for this, but I've been having trouble seeing what the reason is.

**Comment by ezyang** [comment]
The keyword here is "force push" :) If we force push, GitHub loses track of all the previous commits (they no longer show up in the PR description page). By never force pushing, we can maintain consistent history.

**Comment by samestep** [comment]
@ezyang Makes sense to me. So, should we merge this PR as-is?

**Comment by ezyang** [comment]
I guess we might as well dogfood it for a while and see if it works.

**Comment by samestep** [comment]
@ezyang Thinking about this more, I actually think we do want to put in some additional logic to allow rebasing onto a more recent version of `master`. If we don't allow that, wouldn't this prevent people from resolving merge conflicts in some cases?

**Comment by ezyang** [comment]
Err, people don't ever actually attempt merges on the head branch, it's just to make GitHub happy.

**Comment by samestep** [comment]
Ah, ok; I suppose I'll need to look more closely at how `ghimport` works.

**Comment by ezyang** [comment]
It turns out, while HUMANS don't merge with master, CI SCRIPTS do. Test failures at https://app.circleci.com/pipelines/github/pytorch/pytorch/285473/workflows/5709135d-0ef7-448f-8757-fde30622f343/jobs/11551386 due to inaccurate master information

**Pull request merged**
