### PR TITLE
checkout PR number

### PR DESCRIPTION
**Pull request by vmoens**
Same as #263 but for `ghstack checkout`

### CODE REVIEW

**Comment by ezyang** [comment]
also needs test fixes

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
hol 'up. I definitely can have colon in my remote url. You need to account for that case...

**Comment by vmoens** [comment]
That was my guess but I can't tell why these changes broke this test. I can edit the regex pattern perhaps

**Comment by vmoens** [comment]
Ok it's fixed now

**Review by ezyang — APPROVED** [review]

**Pull request merged**
