### PR TITLE
Use a bold arrow to indicate the current PR

### PR DESCRIPTION
**Pull request by samestep**
#69 dealt with the recent GitHub UI change by removing the duplicate bolded PR title from `ghstack`-generated PR descriptions, with the hope that simply bolding the PR number would be enough. However, this unfortunately does not work; see https://github.com/pytorch/pytorch/pull/60204 for an example:

Screen Shot 2021-06-25 at 2 05 06 PM

This PR replaces the ineffective attempt at bolding with a bolded arrow to the left of the PR title and number:

Screen Shot 2021-06-28 at 7 44 28 AM

### CODE REVIEW

**Comment by albanD** [comment]
I was thinking that adding this at the beginning of the line would be better. The line length can be very different, making it hard to find the asterix. It is much simpler at the beginning.

Also I would consider using `->` or something similar which is more obvious than an asterix?

**Comment by samestep** [comment]
@albanD That makes sense to me!

**Comment by samestep** [comment]
@ezyang ready for review

**Comment by ezyang** [comment]
Do you wanna, like use a Unicode emoji or something?  Some possibilities:  ▶️ ⇒ ☞ ➔ ➜

**Review by ezyang — APPROVED** [review]

**Comment by samestep** [comment]
> Do you wanna, like use a Unicode emoji or something? Some possibilities: ▶️ ⇒ ☞ ➔ ➜

hmmm not a bad idea 🧐 I think I'll just leave it as an ASCII arrow in this PR but we can change it to an emoji if you want

**Pull request merged**
