### PR TITLE
autoformat project: `poetry run black .`

### PR DESCRIPTION
**Pull request by bolinfest**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132
* __->__ #131
* #130

### CODE REVIEW

**Comment by ezyang** [comment]
gotta fix ci sry

**Comment by bolinfest** [comment]
Hmm, it appears that `black` and `isort` disagree. Is `isort` necessary if we have `black`?

```
$ poetry run isort . --check --diff
ERROR: /Users/mbolin/src/ghstack/ghstack/submit.py Imports are incorrectly sorted and/or formatted.
--- /Users/mbolin/src/ghstack/ghstack/submit.py:before	2022-12-09 12:53:39.661036
+++ /Users/mbolin/src/ghstack/ghstack/submit.py:after	2022-12-09 13:01:10.779514
@@ -13,13 +13,8 @@
 import ghstack.gpg_sign
 import ghstack.logs
 import ghstack.shell
-from ghstack.types import (
-    GhNumber,
-    GitCommitHash,
-    GitHubNumber,
-    GitHubRepositoryId,
-    GitTreeHash,
-)
+from ghstack.types import (GhNumber, GitCommitHash, GitHubNumber,
+                           GitHubRepositoryId, GitTreeHash)

 # Either "base", "head" or "orig"; which of the ghstack generated
 # branches this diff corresponds to
ERROR: /Users/mbolin/src/ghstack/ghstack/shell.py Imports are incorrectly sorted and/or formatted.
--- /Users/mbolin/src/ghstack/ghstack/shell.py:before	2022-12-09 13:00:16.698580
+++ /Users/mbolin/src/ghstack/ghstack/shell.py:after	2022-12-09 13:01:10.804068
@@ -6,7 +6,8 @@
 import shlex
 import subprocess
 import sys
-from typing import IO, Any, Dict, Optional, Sequence, Tuple, TypeVar, Union, overload
+from typing import (IO, Any, Dict, Optional, Sequence, Tuple, TypeVar, Union,
+                    overload)

 # Shell commands generally return str, but with exitcode=True
 # they return a bool, and if stdout is piped straight to sys.stdout
```

**Comment by bolinfest** [comment]
Ah, I think this solves it:

https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html

**Comment by ezyang** [comment]
We use ufmt on the other project for precisely this reason

**Review by ezyang — APPROVED** [review]

**Pull request merged**
